/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.arcs.rgg.rggnbmod.ui;

import at.ac.arcs.rgg.RGG;
import java.io.Serializable;
import java.util.logging.Logger;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
final class RGGTopComponent extends TopComponent {
    
    private static RGGTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "RGGTopComponent";

    private RGG rgg;
    
    private RGGTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(RGGTopComponent.class, "CTL_RGGTopComponent"));
        setToolTipText(NbBundle.getMessage(RGGTopComponent.class, "HINT_RGGTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    public void setRGG(RGG rgg){
        this.rgg = rgg;
        rggScrollPane.setViewportView(rgg.buildPanel(true, false));
        setName(rgg.getRGGName());
    }

    public RGG getRGG() {
        return rgg;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rggScrollPane = new javax.swing.JScrollPane();
        rggContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        rggScrollPane.setBorder(null);

        rggContainer.setLayout(new java.awt.BorderLayout());
        rggScrollPane.setViewportView(rggContainer);

        add(rggScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rggContainer;
    private javax.swing.JScrollPane rggScrollPane;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized RGGTopComponent getDefault() {
        if (instance == null) {
            instance = new RGGTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the RGGTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized RGGTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(RGGTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof RGGTopComponent) {
            return (RGGTopComponent) win;
        }
        Logger.getLogger(RGGTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
    // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
    // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return RGGTopComponent.getDefault();
        }
    }
}
