createReportSamr = function(object.names,rgghome,qqplot=F,reportfolder=paste(rgghome,"report",sep="/"),delta="not specified",foldchange="not specified"){

dir.create(reportfolder)
file.copy(stylesheet,paste(reportfolder,"style.css",sep="/"), overwrite = T)

if(!dev.interactive()){		
		postscript(file="temp.eps")
		dev.control(displaylist='enable')	
}

report <- HTMLInitFile(reportfolder,filename="samr-report",Title = "samr-report generated by RGG GUI",CSSFile="style.css")
HTML("<center><h1>SAMR-REPORT</h1>")
HTML(paste("generated by RGG GUI, ",date(),"</center><br><br>"))
HTML("<table border=\"0\" align=\"center\">")
HTML("<tr><th class=\"sectionheader\">SAMR results</th></tr>")


if("tailstr" %in% objectnames){
	HTML("<tr><td>")
	HTML(as.data.frame(tailstr),Border=0,innerBorder=1,classfirstline="sectionheader",classfirstcolumn="sectionheader",digits=5,align="center",caption="Estimated tail strength")
	HTML("</td></tr>")
}

if("pval" %in% objectnames){
	HTML("<tr><td>")
	pval2 = as.data.frame(pval[order(as.vector(pval))])
	names(pval2) = "estd. p value"
	HTML(data.frame(gene=rownames(pval2)[1:min(50,nrow(pval2))],estimatedpval=pval2[1:min(50,nrow(pval2)),]),Border=0,innerBorder=1,classfirstline="sectionheader",classfirstcolumn="sectionheader",digits=5,align="center",caption="Estimated p values ( max. 50)")
	HTML("</td></tr>")
}

if("deltatable" %in% objectnames){
	HTML("<tr><td>")
	HTML(as.data.frame(deltatable),Border=0,innerBorder=1,classfirstline="sectionheader",classfirstcolumn="sectionheader",digits=5,align="center",caption="Delta table")
	HTML("</td></tr>")
}
	
HTML(paste("<tr><th class=\"sectionheader\">Calculations done for a delta value of ",delta," and a minimum fold change of: ",foldchange,"</th></tr>",sep=""))
	
if("estdmissrate" %in% objectnames){
	HTML("<tr><td>")
	HTML(as.data.frame(estdmissrate),Border=0,innerBorder=1,classfirstline="sectionheader",classfirstcolumn="sectionheader",digits=5,align="center",caption="Miss rate table")
	HTML("</td></tr>")
}

if(qqplot && names(dev.cur())!="null device"){
	nrppi = 72
	w=8
	h=8
	wd = w*nrppi
	hg = h*nrppi
	names = paste(reportfolder,"/","qqplot",c(".pdf",".png"),sep="")
	dev.print(device=pdf,names[1],width=w,height=h,pointsize=14)
	dev.print(device=png,names[2],width=wd,height=hg,pointsize=10)
	HTML("<tr><td align=\"center\"><a href=\"qqplot.pdf\"><img src=\"qqplot.png\"/></a><br>QQplot</td></tr>")
}

if("siggenestable" %in% objectnames){
	HTML(paste("<tr><th class=\"sectionheader\">Significant genes with positive values: ",siggenestable$ngenes.up,"</th></tr>",sep="")) 
	if(siggenestable$ngenes.up != 0){
		HTML("<tr><td>")
		HTML(as.data.frame(siggenestable$genes.up[1:min(siggenestable$ngenes.up,50),]),Border=0,innerBorder=1,classfirstline="sectionheader",classfirstcolumn="sectionheader",digits=5,align="center",caption="Significant genes with positive values (max. 50)")
		HTML("</td></tr>")
	}
	HTML(paste("<tr><th class=\"sectionheader\">Significant genes with negative values: ",siggenestable$ngenes.lo,"</th></tr>",sep="")) 
	if(siggenestable$ngenes.lo != 0){
		HTML("<tr><td>")
		HTML(as.data.frame(siggenestable$genes.lo[1:min(siggenestable$ngenes.lo,50),]),Border=0,innerBorder=1,classfirstline="sectionheader",classfirstcolumn="sectionheader",digits=5,align="center",caption="Significant genes with positive values (max. 50)")
		HTML("</td></tr>")
	}
}

HTML("</table>")

HTML(paste("Samr-report generated by RGG GUI, ",date(),"<br><br>"))

HTMLEndFile()
}